type = "offchainreporting"
schemaVersion = 1
contractAddress = "0x99Dca838d573a2Bfdf0919AE5f76beC0f475a84c"
p2pPeerID = "12D3KooWFgz6ct88bfsspqPHKtegFyVikCNvuy1h4ADkJbjm8z4X"
p2pBootstrapPeers = [
"/ip4/10.5.0.3/tcp/3002/p2p/12D3KooWFgz6ct88bfsspqPHKtegFyVikCNvuy1h4ADkJbjm8z4X"
]
isBootstrapPeer = false
keyBundleID = "db1f09279d284c1e64a97aa9480e4b2a69ea1e53b41c80830de14b86721170a0"
transmitterAddress = "0x0b8cDAAd06Ca2cc92bb676E1106EA415d81dda2A"
observationTimeout = "20s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m0s"
contractConfigTrackerPollInterval = "1m0s"
contractConfigConfirmations = 1
observationSource = """
    numbers      [type=http method=GET url="http://10.5.0.6:3000/numbers" allowUnrestrictedNetworkAccess=true]
    rid          [type=jsonparse path="rid"]
    values       [type=jsonparse path="values"]
    sum_values   [type=sum values="$(values)"]
    rid_scaled   [type=multiply input="$(rid)" times=18446744073709551616]
    encoded      [type=sum values="[ $(rid_scaled), $(sum_values) ]"]

    numbers -> rid
    numbers -> values -> sum_values
    rid -> rid_scaled
    rid_scaled -> encoded
    sum_values -> encoded
    encoded
"""
maxTaskDuration = "0s"
externalJobID = "b82713fd-8be1-4e45-9d2a-fb6994b0f9f5"
